{% set version = "1.1.0" %}

package:
  name: ndcsv
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/ndcsv/ndcsv-{{ version }}.tar.gz
  sha256: 4f4587d88b953a81398451980d843508ec50b135144c4436e5d9066da8428701

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python >=3.8
    - pip
    - setuptools_scm
  run:
    - python >=3.8
    - numpy >=1.14
    - pandas >=0.24
    - xarray >=0.14
    - pshell >=1.0

test:
  imports:
    - ndcsv
  requires:
    - pytest >=3.8

about:
  home: https://github.com/crusaderky/ndcsv
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: N-Dimensional CSV files for xarray

extra:
  recipe-maintainers:
    - crusaderky
