travis:
  secure:
    BINSTAR_TOKEN: BSdz1Bwr1hwfUbHGcGE6COY8dJqxc9O3pbR9OirMxj/ERkPw8XjLm00f6XcQk7HNrVq7pkbhDf+vCcd9hkwLDGYnHJ3ZKJXHvYZOVolFzwFO+7SP68Ko8iZMCiv+33/rsYZLPfmZzCF3EkFpcHMwBVWWjiSCRSN5djdZkNeh5IprWGag0XuAkXA8nxmkNW9VpJuz0X2kW/mmaM1/BEPHxqOrLlh0vHZR91m3Kc/iQZWDi9wI1ACJe4sqiwofy0VU14k1Bch4IjTfxy9JXr+TBmu0T4hAdIyliO7VqfFMWD++k76IPevU4/UfWAfMQxMT92ABElwYnGKky0MyUqOl5RZVZJR0+DAznlVG3Nr3RROGheFddGMG5r/5mxR0LhzeZ2zgGuHTKCFW8msSkGd2427rm5UG6opRKz7bfXopWVKK/YCilLfWo+L8+e0Lk91/ItYKv4Aca1r+yVvYgngdfci/sgVe1oM9nFQsHIY6r3FRZOh0XYY0gqaQtHlOjEgXhVdIBjtivvQYWzRpxnupdTgDoiCQvqnXzSFNGMEsJsbw9+cPySUEiFb4RWlcNa6rC+ST1vKJS2TCQR09Ifs4MTrJ+AM12wuNtqbMsWRcE4hvyoKYsp6UBJ8mB410ITQAo9PDfWbuD8wLNkHMpoWE/7dIzDLOHrdFcmZM/witHKU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
